# Generated by Django 6.0.6 on 2026-06-07 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_balancesheet_id_alter_profitlossstatement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.DecimalField(decimal_places=2, help_text='Calculated 0-100 ML Score', max_digits=5)),
                ('health_label', models.CharField(help_text='Excellent, Good, Stable, Weak, Critical', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_score', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='e.g., debt_to_equity_ratio, sales_growth', max_length=50)),
                ('z_score', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='companies.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.fiscalyear')),
            ],
            options={
                'unique_together': {('company', 'year', 'metric_name')},
            },
        ),
    ]
