# Generated by Django 6.0.6 on 2026-06-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'dim_company',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('year_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_label', models.CharField(max_length=10)),
                ('is_ttm', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'db_table': 'dim_year',
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_capital', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('reserves', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('borrowings', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('other_liabilities', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('year', models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.CASCADE, to='companies.fiscalyear')),
            ],
            options={
                'db_table': 'fact_balance_sheet',
            },
        ),
        migrations.CreateModel(
            name='ProfitLossStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('opm_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sales_growth', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('year', models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.CASCADE, to='companies.fiscalyear')),
            ],
            options={
                'db_table': 'fact_profit_loss',
            },
        ),
    ]
