# Generated by Django 6.0.6 on 2026-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profitlossstatement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
